In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gzip
import os

#### Loading Dataset

In [2]:
data_path = "../data/usc-x-24-us-election/part_1/"

files = [
    "may_july_chunk_1.csv.gz",
    "may_july_chunk_2.csv.gz",
    "may_july_chunk_3.csv.gz",
    "may_july_chunk_4.csv.gz",
    "may_july_chunk_5.csv.gz"
]

In [3]:
df_sample = pd.read_csv(data_path + files[0], compression='gzip')
df_sample.head()

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,quotedTweet,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type
0,0,1801041792923578484,@lukepbeasley I cant imagine anyone actually f...,https://twitter.com/orgneyezedchaos/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792923578484,...,False,lukepbeasley,1.800681e+18,1.483596e+18,NaN,NaN,"{'id': 942869257108455424, 'id_str': '94286925...",2024-06-12,NaN,tweet-
1,1,1801041792630227173,Voters can also sway me away from voting for ...,https://twitter.com/Brandon62294232/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792630227173,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1461100431329796100, 'id_str': '1461100...",2024-06-12,NaN,tweet-
2,2,1801041792592224521,@PoodleHead57 @BobOnderMO Can you name that am...,https://twitter.com/JohnRMBR911/status/1801041...,1.718237e+09,[],False,NaN,NaN,1801041792592224521,...,False,PoodleHead57,1.801030e+18,1.480159e+18,NaN,NaN,"{'id': 1655734665955737600, 'id_str': '1655734...",2024-06-12,NaN,tweet-
3,3,1801041791463866688,@Morning_Joe @JoeNBC The fact remains that Joe...,https://twitter.com/andy_leq/status/1801041791...,1.718237e+09,[],False,NaN,NaN,1801041791463866688,...,False,Morning_Joe,1.800873e+18,2.541174e+08,NaN,NaN,"{'id': 1771777682587713536, 'id_str': '1771777...",2024-06-12,NaN,tweet-
4,4,1801041790952231228,@BidenHQ That's funny you're obviously trying ...,https://twitter.com/Ranchhandlb7/status/180104...,1.718237e+09,[],False,NaN,NaN,1801041790952231228,...,False,KamalaHQ,1.800703e+18,3.315265e+09,NaN,NaN,"{'id': 874708668, 'id_str': '874708668', 'url'...",2024-06-12,NaN,tweet-

In [4]:
df_sample.columns

Index(['Unnamed: 0', 'id', 'text', 'url', 'epoch', 'media', 'retweetedTweet',
       'retweetedTweetID', 'retweetedUserID', 'id_str', 'lang', 'rawContent',
       'replyCount', 'retweetCount', 'likeCount', 'quoteCount',
       'conversationId', 'conversationIdStr', 'hashtags', 'mentionedUsers',
       'links', 'viewCount', 'quotedTweet', 'in_reply_to_screen_name',
       'in_reply_to_status_id_str', 'in_reply_to_user_id_str', 'location',
       'cash_app_handle', 'user', 'date', '_type', 'type'],
      dtype='str')

#### Load All 5 Chunks

In [5]:
dfs = []
for f in files:
    print("Loading:", f)
    temp = pd.read_csv(data_path + f, compression='gzip')
    dfs.append(temp)

df = pd.concat(dfs, ignore_index=True)

print("Total rows:", len(df))
df.head()

Loading: may_july_chunk_1.csv.gz
Loading: may_july_chunk_2.csv.gz
Loading: may_july_chunk_3.csv.gz
Loading: may_july_chunk_4.csv.gz
Loading: may_july_chunk_5.csv.gz
Total rows: 250000

,Unnamed: 0,id,text,url,epoch,media,retweetedTweet,retweetedTweetID,retweetedUserID,id_str,...,quotedTweet,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,location,cash_app_handle,user,date,_type,type
0,0,1801041792923578484,@lukepbeasley I cant imagine anyone actually f...,https://twitter.com/orgneyezedchaos/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792923578484,...,False,lukepbeasley,1.800681e+18,1.483596e+18,NaN,NaN,"{'id': 942869257108455424, 'id_str': '94286925...",2024-06-12,NaN,tweet-
1,1,1801041792630227173,Voters can also sway me away from voting for ...,https://twitter.com/Brandon62294232/status/180...,1.718237e+09,[],False,NaN,NaN,1801041792630227173,...,False,NaN,NaN,NaN,NaN,NaN,"{'id': 1461100431329796100, 'id_str': '1461100...",2024-06-12,NaN,tweet-
2,2,1801041792592224521,@PoodleHead57 @BobOnderMO Can you name that am...,https://twitter.com/JohnRMBR911/status/1801041...,1.718237e+09,[],False,NaN,NaN,1801041792592224521,...,False,PoodleHead57,1.801030e+18,1.480159e+18,NaN,NaN,"{'id': 1655734665955737600, 'id_str': '1655734...",2024-06-12,NaN,tweet-
3,3,1801041791463866688,@Morning_Joe @JoeNBC The fact remains that Joe...,https://twitter.com/andy_leq/status/1801041791...,1.718237e+09,[],False,NaN,NaN,1801041791463866688,...,False,Morning_Joe,1.800873e+18,2.541174e+08,NaN,NaN,"{'id': 1771777682587713536, 'id_str': '1771777...",2024-06-12,NaN,tweet-
4,4,1801041790952231228,@BidenHQ That's funny you're obviously trying ...,https://twitter.com/Ranchhandlb7/status/180104...,1.718237e+09,[],False,NaN,NaN,1801041790952231228,...,False,KamalaHQ,1.800703e+18,3.315265e+09,NaN,NaN,"{'id': 874708668, 'id_str': '874708668', 'url'...",2024-06-12,NaN,tweet-

#### Dataset Stats

In [6]:
stats = {
    "Total Tweets": len(df),
    "Unique Users": df['user'].nunique(),
    "Unique Conversations": df['conversationId'].nunique(),
    "Total Retweets": df['retweetedTweet'].notna().sum(),
    "Total Replies": df['in_reply_to_user_id_str'].notna().sum(),
    "Total Quotes": df['quotedTweet'].notna().sum(),
    "Total Tweets with Hashtags": df['hashtags'].notna().sum(),
    "Total Tweets with Mentions": df['mentionedUsers'].notna().sum(),
    "Total Tweets with Links": df['links'].notna().sum(),
    "Languages Used": df['lang'].nunique()
}

stats_df = pd.DataFrame(list(stats.items()), columns=['Metric', 'Value'])
stats_df

                       Metric   Value
0                Total Tweets  250000
1                Unique Users  200559
2        Unique Conversations  111397
3              Total Retweets  250000
4               Total Replies  180040
5                Total Quotes  250000
6  Total Tweets with Hashtags  250000
7  Total Tweets with Mentions  250000
8     Total Tweets with Links  250000
9              Languages Used      56

In [25]:
import plotly.express as px

fig = px.bar(
    stats_df,
    x='Metric',
    y='Value',
    title='Dataset Statistics',
    text='Value'
)

fig.update_layout(xaxis_tickangle=-45)
fig.show()

#### Tweet Interaction Types

In [33]:
interaction_counts = {
    "Hashtags": df['hashtags'].notna().sum(),
    "Mentions": df['mentionedUsers'].notna().sum(),
    "Links": df['links'].notna().sum(),
    "Replies": df['in_reply_to_user_id_str'].notna().sum(),
    "Retweets": df['retweetedTweet'].notna().sum(),
    "Quotes": df['quotedTweet'].notna().sum()
}

interaction_df = pd.DataFrame(list(interaction_counts.items()), columns=['Type', 'Count'])

fig = px.pie(interaction_df, names='Type', values='Count', hole =0.3, title='Tweet Interaction Types')
fig.update_traces(
    textinfo='label+percent+value'
)
fig.show()

#### Engagement Distribution

In [34]:
engagement_cols = ['replyCount', 'retweetCount', 'likeCount', 'quoteCount']

engagement_df = df[engagement_cols].fillna(0)
engagement_sum = engagement_df.sum()

import plotly.express as px

fig = px.pie(
    names=engagement_sum.index,
    values=engagement_sum.values,
    hole = 0.3,
    title='Engagement Distribution'
)

fig.update_traces(
    textinfo='label+percent+value'
)

fig.show()

In [10]:
df['date'] = pd.to_datetime(df['date'])

print("Start date:", df['date'].min())
print("End date:", df['date'].max())

Start date: 2024-06-12 00:00:00
End date: 2024-06-12 00:00:00

#### Top Hashtags

In [12]:
df['hashtags'].dropna().head(10)

0                                                   []
1                                                   []
2    [{'indices': [171, 176], 'text': 'MAGA'}, {'in...
3                                                   []
4                                                   []
5      [{'indices': [0, 14], 'text': 'Internacional'}]
6                                                   []
7                                                   []
8                                                   []
9                                                   []
Name: hashtags, dtype: str

In [29]:
import ast
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

def extract_hashtag_text(x):
    if pd.isna(x):
        return []
    try:
        tags = ast.literal_eval(x)
        return [t['text'] for t in tags if 'text' in t]
    except:
        return []

df['hashtags_list'] = df['hashtags'].apply(extract_hashtag_text)

all_tags = [tag for sublist in df['hashtags_list'] for tag in sublist]

# tag_counts = pd.Series(all_tags).value_counts().head(20).reset_index()
tag_counts = pd.Series(all_tags).value_counts().reset_index()
tag_counts.columns = ['hashtag', 'count']

# Take top 20
tag_counts = tag_counts.head(20)

# Sort so largest appears on top in horizontal bar
tag_counts = tag_counts.sort_values(by='count', ascending=True)

fig = go.Figure(
    go.Bar(
        x=tag_counts['count'],
        y=tag_counts['hashtag'],
        orientation='h'
    )
)

fig.update_layout(
    title='Top 20 Hashtags',
    xaxis_title='Count',
    yaxis_title='Hashtag',
    yaxis=dict(
        tickmode='array',
        tickvals=tag_counts['hashtag'],
        ticktext=tag_counts['hashtag']
    )
)

fig.show()

#### Retweet vs Reply Counts

In [15]:
retweets = df['retweetedTweet'].notna().sum()
replies = df['in_reply_to_user_id_str'].notna().sum()

interaction_df = pd.DataFrame({
    'type': ['Retweets', 'Replies'],
    'count': [retweets, replies]
})

fig = px.bar(interaction_df, x='type', y='count', title='Retweets vs Replies')
fig.show()